#pragma checksum "Location\pgLocationSublocations.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "14E379436108D4DA0C7C96DA2D19AE9C5DECC86DC3E1D3A1660CC25C518D0915"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Location;


namespace WPFPresentation.Location {
    
    
    /// <summary>
    /// pgLocationSublocations
    /// </summary>
    public partial class pgLocationSublocations : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLocationAreasMainName;
        
        #line default
        #line hidden
        
        
        #line 22 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnEdit;
        
        #line default
        #line hidden
        
        
        #line 23 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAdd;
        
        #line default
        #line hidden
        
        
        #line 24 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer scrSublocations;
        
        #line default
        #line hidden
        
        
        #line 25 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdSublocationsRows;
        
        #line default
        #line hidden
        
        
        #line 34 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSublocationName;
        
        #line default
        #line hidden
        
        
        #line 35 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSublocationDescription;
        
        #line default
        #line hidden
        
        
        #line 36 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSublocationName;
        
        #line default
        #line hidden
        
        
        #line 37 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDelete0;
        
        #line default
        #line hidden
        
        
        #line 43 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdAddsublocation;
        
        #line default
        #line hidden
        
        
        #line 44 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAddSublocationName;
        
        #line default
        #line hidden
        
        
        #line 45 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNewSublocationName;
        
        #line default
        #line hidden
        
        
        #line 47 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAddSublocationDesc;
        
        #line default
        #line hidden
        
        
        #line 48 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNewSublocationDesc;
        
        #line default
        #line hidden
        
        
        #line 50 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddNewSublocation;
        
        #line default
        #line hidden
        
        
        #line 51 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 54 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveAreas;
        
        #line default
        #line hidden
        
        
        #line 55 "Location\pgLocationSublocations.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancelEditAreas;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/location/pglocationsublocations.xaml", System.UriKind.Relative);
            
            #line 1 "Location\pgLocationSublocations.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Location\pgLocationSublocations.xaml"
            ((WPFPresentation.Location.pgLocationSublocations)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblLocationAreasMainName = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.btnEdit = ((System.Windows.Controls.Button)(target));
            
            #line 22 "Location\pgLocationSublocations.xaml"
            this.btnEdit.Click += new System.Windows.RoutedEventHandler(this.btnEdit_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 23 "Location\pgLocationSublocations.xaml"
            this.btnAdd.Click += new System.Windows.RoutedEventHandler(this.btnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.scrSublocations = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 6:
            this.grdSublocationsRows = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.lblSublocationName = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.txtSublocationDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.txtSublocationName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.btnDelete0 = ((System.Windows.Controls.Button)(target));
            
            #line 37 "Location\pgLocationSublocations.xaml"
            this.btnDelete0.Click += new System.Windows.RoutedEventHandler(this.btnDelete0_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.grdAddsublocation = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.lblAddSublocationName = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.txtNewSublocationName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.lblAddSublocationDesc = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.txtNewSublocationDesc = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.btnAddNewSublocation = ((System.Windows.Controls.Button)(target));
            
            #line 50 "Location\pgLocationSublocations.xaml"
            this.btnAddNewSublocation.Click += new System.Windows.RoutedEventHandler(this.btnAddNewSublocation_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 51 "Location\pgLocationSublocations.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.btnSaveAreas = ((System.Windows.Controls.Button)(target));
            
            #line 54 "Location\pgLocationSublocations.xaml"
            this.btnSaveAreas.Click += new System.Windows.RoutedEventHandler(this.btnSaveAreas_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.btnCancelEditAreas = ((System.Windows.Controls.Button)(target));
            
            #line 55 "Location\pgLocationSublocations.xaml"
            this.btnCancelEditAreas.Click += new System.Windows.RoutedEventHandler(this.btnCancelEditAreas_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

