#pragma checksum "Location\pgParkingLot.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7B051F7D4F6784DF2BE090CEE55382F6A0BF9A51F799606ED40D4443DB1495AA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Location;


namespace WPFPresentation.Location {
    
    
    /// <summary>
    /// pgParkingLot
    /// </summary>
    public partial class pgParkingLot : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 24 "Location\pgParkingLot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtLocationName;
        
        #line default
        #line hidden
        
        
        #line 25 "Location\pgParkingLot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddParkingLot;
        
        #line default
        #line hidden
        
        
        #line 51 "Location\pgParkingLot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl icParkingLots;
        
        #line default
        #line hidden
        
        
        #line 131 "Location\pgParkingLot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlockErrors;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/location/pgparkinglot.xaml", System.UriKind.Relative);
            
            #line 1 "Location\pgParkingLot.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtLocationName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.btnAddParkingLot = ((System.Windows.Controls.Button)(target));
            
            #line 25 "Location\pgParkingLot.xaml"
            this.btnAddParkingLot.Click += new System.Windows.RoutedEventHandler(this.btnAddParkingLot_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.icParkingLots = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 12:
            this.txtBlockErrors = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 4:
            
            #line 72 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.TextBox)(target)).Initialized += new System.EventHandler(this.TextBox_Initialized);
            
            #line default
            #line hidden
            break;
            case 5:
            
            #line 73 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Initialized += new System.EventHandler(this.Button_Initialized);
            
            #line default
            #line hidden
            
            #line 73 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelButtonClick);
            
            #line default
            #line hidden
            break;
            case 6:
            
            #line 74 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Initialized += new System.EventHandler(this.Button_Initialized);
            
            #line default
            #line hidden
            
            #line 74 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveButton_Click);
            
            #line default
            #line hidden
            break;
            case 7:
            
            #line 96 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Initialized += new System.EventHandler(this.DeleteButton_Initialized);
            
            #line default
            #line hidden
            
            #line 96 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteButton_Click);
            
            #line default
            #line hidden
            break;
            case 8:
            
            #line 118 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Initialized += new System.EventHandler(this.EditButton_Initialized);
            
            #line default
            #line hidden
            
            #line 118 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditButton_Click);
            
            #line default
            #line hidden
            break;
            case 9:
            
            #line 121 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Image)(target)).Initialized += new System.EventHandler(this.Image_Initialized);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 122 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Initialized += new System.EventHandler(this.Button_Initialized);
            
            #line default
            #line hidden
            
            #line 122 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btnAddImage);
            
            #line default
            #line hidden
            break;
            case 11:
            
            #line 124 "Location\pgParkingLot.xaml"
            ((System.Windows.Controls.TextBox)(target)).Initialized += new System.EventHandler(this.TextBox_Initialized);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

