#pragma checksum "Event\pgEventFrame.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1E3DB0AA789EF18232A1E338F82C0B508727805A06CAA8F157A373A7C626676C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Event;


namespace WPFPresentation.Event {
    
    
    /// <summary>
    /// pgEventFrame
    /// </summary>
    public partial class pgEventFrame : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "Event\pgEventFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal WPFPresentation.Event.pgEventFrame frmEventFrame;
        
        #line default
        #line hidden
        
        
        #line 29 "Event\pgEventFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnEventDetails;
        
        #line default
        #line hidden
        
        
        #line 30 "Event\pgEventFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTasks;
        
        #line default
        #line hidden
        
        
        #line 31 "Event\pgEventFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnItinerary;
        
        #line default
        #line hidden
        
        
        #line 38 "Event\pgEventFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame EventFrame;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/event/pgeventframe.xaml", System.UriKind.Relative);
            
            #line 1 "Event\pgEventFrame.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.frmEventFrame = ((WPFPresentation.Event.pgEventFrame)(target));
            
            #line 9 "Event\pgEventFrame.xaml"
            this.frmEventFrame.Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnEventDetails = ((System.Windows.Controls.Button)(target));
            
            #line 29 "Event\pgEventFrame.xaml"
            this.btnEventDetails.Click += new System.Windows.RoutedEventHandler(this.btnEventDetails_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnTasks = ((System.Windows.Controls.Button)(target));
            
            #line 30 "Event\pgEventFrame.xaml"
            this.btnTasks.Click += new System.Windows.RoutedEventHandler(this.btnTasks_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnItinerary = ((System.Windows.Controls.Button)(target));
            
            #line 31 "Event\pgEventFrame.xaml"
            this.btnItinerary.Click += new System.Windows.RoutedEventHandler(this.btnItinerary_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.EventFrame = ((System.Windows.Controls.Frame)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

