#pragma checksum "Event\pgTaskListEdit.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "24744CB70BE2DBCBAB7C879D437DEBCDE3D113B78BC280BDF635B97762B9C85B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Event;


namespace WPFPresentation.Event {
    
    
    /// <summary>
    /// pgTaskListEdit
    /// </summary>
    public partial class pgTaskListEdit : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkEditTaskList;
        
        #line default
        #line hidden
        
        
        #line 41 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkEventName;
        
        #line default
        #line hidden
        
        
        #line 44 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkTaskName;
        
        #line default
        #line hidden
        
        
        #line 46 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTaskName;
        
        #line default
        #line hidden
        
        
        #line 48 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkTaskDescription;
        
        #line default
        #line hidden
        
        
        #line 50 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTaskDescription;
        
        #line default
        #line hidden
        
        
        #line 53 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkTaskAssign;
        
        #line default
        #line hidden
        
        
        #line 55 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cboAssign;
        
        #line default
        #line hidden
        
        
        #line 57 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkTaskDueDate;
        
        #line default
        #line hidden
        
        
        #line 59 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dtpTaskDueDate;
        
        #line default
        #line hidden
        
        
        #line 61 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkPriority;
        
        #line default
        #line hidden
        
        
        #line 63 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cboPriority;
        
        #line default
        #line hidden
        
        
        #line 64 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlkVolunteerNeed;
        
        #line default
        #line hidden
        
        
        #line 66 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel dcPnlNumVolunteers;
        
        #line default
        #line hidden
        
        
        #line 68 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider sldrNumVolunteers;
        
        #line default
        #line hidden
        
        
        #line 78 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveTask;
        
        #line default
        #line hidden
        
        
        #line 79 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancelTask;
        
        #line default
        #line hidden
        
        
        #line 80 "Event\pgTaskListEdit.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDeleteTask;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/event/pgtasklistedit.xaml", System.UriKind.Relative);
            
            #line 1 "Event\pgTaskListEdit.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Event\pgTaskListEdit.xaml"
            ((WPFPresentation.Event.pgTaskListEdit)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.txtBlkEditTaskList = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.txtBlkEventName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.txtBlkTaskName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.txtTaskName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.txtBlkTaskDescription = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.txtTaskDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtBlkTaskAssign = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.cboAssign = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.txtBlkTaskDueDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.dtpTaskDueDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 12:
            this.txtBlkPriority = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.cboPriority = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.txtBlkVolunteerNeed = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.dcPnlNumVolunteers = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 16:
            this.sldrNumVolunteers = ((System.Windows.Controls.Slider)(target));
            return;
            case 17:
            this.btnSaveTask = ((System.Windows.Controls.Button)(target));
            
            #line 78 "Event\pgTaskListEdit.xaml"
            this.btnSaveTask.Click += new System.Windows.RoutedEventHandler(this.btnSaveTask_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.btnCancelTask = ((System.Windows.Controls.Button)(target));
            
            #line 79 "Event\pgTaskListEdit.xaml"
            this.btnCancelTask.Click += new System.Windows.RoutedEventHandler(this.btnCancelTask_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.btnDeleteTask = ((System.Windows.Controls.Button)(target));
            
            #line 80 "Event\pgTaskListEdit.xaml"
            this.btnDeleteTask.Click += new System.Windows.RoutedEventHandler(this.btnDeleteTask_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

