#pragma checksum "Event\pgViewActivities.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C991394D54DBA00814BA1D076617BBC47C47EAE09013F3AE6386B81C9FC5ED04"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Event;


namespace WPFPresentation.Event {
    
    
    /// <summary>
    /// pgViewActivities
    /// </summary>
    public partial class pgViewActivities : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stckPanEventActivityFilter;
        
        #line default
        #line hidden
        
        
        #line 18 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cboEventActivityFilter;
        
        #line default
        #line hidden
        
        
        #line 20 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBoxItem cmbItemsChooseFilter;
        
        #line default
        #line hidden
        
        
        #line 21 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stckFilterItems;
        
        #line default
        #line hidden
        
        
        #line 24 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radActivityDateFilter;
        
        #line default
        #line hidden
        
        
        #line 25 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radActivtyNameFilter;
        
        #line default
        #line hidden
        
        
        #line 26 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radActivitySublocationFilter;
        
        #line default
        #line hidden
        
        
        #line 27 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton radAllActivities;
        
        #line default
        #line hidden
        
        
        #line 32 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSearch;
        
        #line default
        #line hidden
        
        
        #line 33 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker datePickerActivityDate;
        
        #line default
        #line hidden
        
        
        #line 34 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSearch;
        
        #line default
        #line hidden
        
        
        #line 35 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnFind;
        
        #line default
        #line hidden
        
        
        #line 37 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblActivityEventName;
        
        #line default
        #line hidden
        
        
        #line 38 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddActivity;
        
        #line default
        #line hidden
        
        
        #line 39 "Event\pgViewActivities.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datEventActivities;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/event/pgviewactivities.xaml", System.UriKind.Relative);
            
            #line 1 "Event\pgViewActivities.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Event\pgViewActivities.xaml"
            ((WPFPresentation.Event.pgViewActivities)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.stckPanEventActivityFilter = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.cboEventActivityFilter = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.cmbItemsChooseFilter = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 5:
            this.stckFilterItems = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.radActivityDateFilter = ((System.Windows.Controls.RadioButton)(target));
            
            #line 24 "Event\pgViewActivities.xaml"
            this.radActivityDateFilter.Click += new System.Windows.RoutedEventHandler(this.radActivityFilterClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.radActivtyNameFilter = ((System.Windows.Controls.RadioButton)(target));
            
            #line 25 "Event\pgViewActivities.xaml"
            this.radActivtyNameFilter.Click += new System.Windows.RoutedEventHandler(this.radActivityFilterClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.radActivitySublocationFilter = ((System.Windows.Controls.RadioButton)(target));
            
            #line 26 "Event\pgViewActivities.xaml"
            this.radActivitySublocationFilter.Click += new System.Windows.RoutedEventHandler(this.radActivityFilterClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.radAllActivities = ((System.Windows.Controls.RadioButton)(target));
            
            #line 27 "Event\pgViewActivities.xaml"
            this.radAllActivities.Click += new System.Windows.RoutedEventHandler(this.radActivityFilterClick);
            
            #line default
            #line hidden
            return;
            case 10:
            this.lblSearch = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.datePickerActivityDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 12:
            this.txtSearch = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.btnFind = ((System.Windows.Controls.Button)(target));
            
            #line 35 "Event\pgViewActivities.xaml"
            this.btnFind.Click += new System.Windows.RoutedEventHandler(this.btnFind_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.lblActivityEventName = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.btnAddActivity = ((System.Windows.Controls.Button)(target));
            
            #line 38 "Event\pgViewActivities.xaml"
            this.btnAddActivity.Click += new System.Windows.RoutedEventHandler(this.btnAddActivity_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.datEventActivities = ((System.Windows.Controls.DataGrid)(target));
            
            #line 39 "Event\pgViewActivities.xaml"
            this.datEventActivities.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.datEventActivities_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

