#pragma checksum "Supplier\pgSupplierDetails.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "483413717E224C8476D5E7266EB5D6803FF121A2ADE28D3F6B5497078AD8B411"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.Supplier;


namespace WPFPresentation.Supplier {
    
    
    /// <summary>
    /// pgSupplierDetails
    /// </summary>
    public partial class pgSupplierDetails : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblName;
        
        #line default
        #line hidden
        
        
        #line 19 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathFavorite;
        
        #line default
        #line hidden
        
        
        #line 22 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnFavorite;
        
        #line default
        #line hidden
        
        
        #line 46 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblType;
        
        #line default
        #line hidden
        
        
        #line 47 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAbout;
        
        #line default
        #line hidden
        
        
        #line 48 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtAbout;
        
        #line default
        #line hidden
        
        
        #line 49 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTags;
        
        #line default
        #line hidden
        
        
        #line 57 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhone;
        
        #line default
        #line hidden
        
        
        #line 58 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmail;
        
        #line default
        #line hidden
        
        
        #line 60 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhotoHeading;
        
        #line default
        #line hidden
        
        
        #line 67 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgSupplier;
        
        #line default
        #line hidden
        
        
        #line 68 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 69 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNext;
        
        #line default
        #line hidden
        
        
        #line 72 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canStarRating;
        
        #line default
        #line hidden
        
        
        #line 76 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarOne;
        
        #line default
        #line hidden
        
        
        #line 79 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarTwo;
        
        #line default
        #line hidden
        
        
        #line 82 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarThree;
        
        #line default
        #line hidden
        
        
        #line 85 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFour;
        
        #line default
        #line hidden
        
        
        #line 88 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFive;
        
        #line default
        #line hidden
        
        
        #line 92 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFirstReview;
        
        #line default
        #line hidden
        
        
        #line 93 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSecondReview;
        
        #line default
        #line hidden
        
        
        #line 94 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMoreReviews;
        
        #line default
        #line hidden
        
        
        #line 95 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnRequestReservation;
        
        #line default
        #line hidden
        
        
        #line 96 "Supplier\pgSupplierDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSendMessage;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/supplier/pgsupplierdetails.xaml", System.UriKind.Relative);
            
            #line 1 "Supplier\pgSupplierDetails.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Supplier\pgSupplierDetails.xaml"
            ((WPFPresentation.Supplier.pgSupplierDetails)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblName = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.pathFavorite = ((System.Windows.Shapes.Path)(target));
            return;
            case 4:
            this.btnFavorite = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.lblType = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblAbout = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.txtAbout = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.lblTags = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.lblPhone = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.lblEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.lblPhotoHeading = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.imgSupplier = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            return;
            case 14:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            return;
            case 15:
            this.canStarRating = ((System.Windows.Controls.Canvas)(target));
            return;
            case 16:
            this.pathStarOne = ((System.Windows.Shapes.Path)(target));
            return;
            case 17:
            this.pathStarTwo = ((System.Windows.Shapes.Path)(target));
            return;
            case 18:
            this.pathStarThree = ((System.Windows.Shapes.Path)(target));
            return;
            case 19:
            this.pathStarFour = ((System.Windows.Shapes.Path)(target));
            return;
            case 20:
            this.pathStarFive = ((System.Windows.Shapes.Path)(target));
            return;
            case 21:
            this.txtFirstReview = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.txtSecondReview = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.btnMoreReviews = ((System.Windows.Controls.Button)(target));
            return;
            case 24:
            this.btnRequestReservation = ((System.Windows.Controls.Button)(target));
            return;
            case 25:
            this.btnSendMessage = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

