#pragma checksum "Supplier\pgViewSupplierListing.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5B817E0F42844C58626C2F550D7376B37D0FFCECAA1F89C084CF34AF9091BFDC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.CustomControls;
using WPFPresentation.Supplier;


namespace WPFPresentation.Supplier {
    
    
    /// <summary>
    /// pgViewSupplierListing
    /// </summary>
    public partial class pgViewSupplierListing : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 24 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSupplierDetails;
        
        #line default
        #line hidden
        
        
        #line 25 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSupplierSchedule;
        
        #line default
        #line hidden
        
        
        #line 26 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSupplierPricing;
        
        #line default
        #line hidden
        
        
        #line 27 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnRequestSupplier;
        
        #line default
        #line hidden
        
        
        #line 30 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdSupplierListing;
        
        #line default
        #line hidden
        
        
        #line 53 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblName;
        
        #line default
        #line hidden
        
        
        #line 56 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathFavorite;
        
        #line default
        #line hidden
        
        
        #line 59 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnFavorite;
        
        #line default
        #line hidden
        
        
        #line 62 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblType;
        
        #line default
        #line hidden
        
        
        #line 63 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAbout;
        
        #line default
        #line hidden
        
        
        #line 64 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtAbout;
        
        #line default
        #line hidden
        
        
        #line 65 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTags;
        
        #line default
        #line hidden
        
        
        #line 73 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhone;
        
        #line default
        #line hidden
        
        
        #line 74 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmail;
        
        #line default
        #line hidden
        
        
        #line 76 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhotoHeading;
        
        #line default
        #line hidden
        
        
        #line 83 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgSupplier;
        
        #line default
        #line hidden
        
        
        #line 84 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 85 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNext;
        
        #line default
        #line hidden
        
        
        #line 88 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canStarRating;
        
        #line default
        #line hidden
        
        
        #line 92 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarOne;
        
        #line default
        #line hidden
        
        
        #line 95 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarTwo;
        
        #line default
        #line hidden
        
        
        #line 98 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarThree;
        
        #line default
        #line hidden
        
        
        #line 101 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFour;
        
        #line default
        #line hidden
        
        
        #line 104 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFive;
        
        #line default
        #line hidden
        
        
        #line 108 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFirstReview;
        
        #line default
        #line hidden
        
        
        #line 109 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSecondReview;
        
        #line default
        #line hidden
        
        
        #line 110 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMoreReviews;
        
        #line default
        #line hidden
        
        
        #line 111 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnRequestReservation;
        
        #line default
        #line hidden
        
        
        #line 112 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSendMessage;
        
        #line default
        #line hidden
        
        
        #line 114 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdSupplierSchedule;
        
        #line default
        #line hidden
        
        
        #line 121 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtSupplierSchedule;
        
        #line default
        #line hidden
        
        
        #line 122 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar calSupplierCalendar;
        
        #line default
        #line hidden
        
        
        #line 133 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblSupplierDate;
        
        #line default
        #line hidden
        
        
        #line 137 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datSupplierActivities;
        
        #line default
        #line hidden
        
        
        #line 149 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datSupplierAvailabilities;
        
        #line default
        #line hidden
        
        
        #line 159 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdSupplierPricing;
        
        #line default
        #line hidden
        
        
        #line 165 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtSupplierServices;
        
        #line default
        #line hidden
        
        
        #line 178 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid imageDataGrid;
        
        #line default
        #line hidden
        
        
        #line 192 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn colServiceName;
        
        #line default
        #line hidden
        
        
        #line 193 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn colServicePrice;
        
        #line default
        #line hidden
        
        
        #line 194 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn colServiceDescription;
        
        #line default
        #line hidden
        
        
        #line 208 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer grdRequestSupplier;
        
        #line default
        #line hidden
        
        
        #line 221 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNameSupplierRequest;
        
        #line default
        #line hidden
        
        
        #line 227 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhoneSupplierRequest;
        
        #line default
        #line hidden
        
        
        #line 231 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmailSupplierRequest;
        
        #line default
        #line hidden
        
        
        #line 258 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboEventSelection;
        
        #line default
        #line hidden
        
        
        #line 265 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stckPnlStartAndEndTimes;
        
        #line default
        #line hidden
        
        
        #line 267 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chckBoxOnlyForEvents;
        
        #line default
        #line hidden
        
        
        #line 268 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker datePickerRequestDate;
        
        #line default
        #line hidden
        
        
        #line 269 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboEventDates;
        
        #line default
        #line hidden
        
        
        #line 276 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtBlockNoDatesForEvent;
        
        #line default
        #line hidden
        
        
        #line 279 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal WPFPresentation.CustomControls.SpecificStartAndEndTimesComboBox cmboStartandEndTimeRequest;
        
        #line default
        #line hidden
        
        
        #line 281 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSelectService;
        
        #line default
        #line hidden
        
        
        #line 282 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer scrollViewerServices;
        
        #line default
        #line hidden
        
        
        #line 283 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl icServices;
        
        #line default
        #line hidden
        
        
        #line 301 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAdditionalComments;
        
        #line default
        #line hidden
        
        
        #line 302 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtAdditionalComments;
        
        #line default
        #line hidden
        
        
        #line 303 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stckSendCancel;
        
        #line default
        #line hidden
        
        
        #line 304 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSendRequest;
        
        #line default
        #line hidden
        
        
        #line 305 "Supplier\pgViewSupplierListing.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancelRequest;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/supplier/pgviewsupplierlisting.xaml", System.UriKind.Relative);
            
            #line 1 "Supplier\pgViewSupplierListing.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "Supplier\pgViewSupplierListing.xaml"
            ((WPFPresentation.Supplier.pgViewSupplierListing)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSupplierDetails = ((System.Windows.Controls.Button)(target));
            
            #line 24 "Supplier\pgViewSupplierListing.xaml"
            this.btnSupplierDetails.Click += new System.Windows.RoutedEventHandler(this.btnSupplierDetails_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnSupplierSchedule = ((System.Windows.Controls.Button)(target));
            
            #line 25 "Supplier\pgViewSupplierListing.xaml"
            this.btnSupplierSchedule.Click += new System.Windows.RoutedEventHandler(this.btnSupplierSchedule_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnSupplierPricing = ((System.Windows.Controls.Button)(target));
            
            #line 26 "Supplier\pgViewSupplierListing.xaml"
            this.btnSupplierPricing.Click += new System.Windows.RoutedEventHandler(this.btnSupplierPricing_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnRequestSupplier = ((System.Windows.Controls.Button)(target));
            
            #line 27 "Supplier\pgViewSupplierListing.xaml"
            this.btnRequestSupplier.Click += new System.Windows.RoutedEventHandler(this.btnRequestSupplier_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.grdSupplierListing = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.lblName = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.pathFavorite = ((System.Windows.Shapes.Path)(target));
            return;
            case 9:
            this.btnFavorite = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.lblType = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.lblAbout = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.txtAbout = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.lblTags = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.lblPhone = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.lblEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.lblPhotoHeading = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.imgSupplier = ((System.Windows.Controls.Image)(target));
            return;
            case 18:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.canStarRating = ((System.Windows.Controls.Canvas)(target));
            return;
            case 21:
            this.pathStarOne = ((System.Windows.Shapes.Path)(target));
            return;
            case 22:
            this.pathStarTwo = ((System.Windows.Shapes.Path)(target));
            return;
            case 23:
            this.pathStarThree = ((System.Windows.Shapes.Path)(target));
            return;
            case 24:
            this.pathStarFour = ((System.Windows.Shapes.Path)(target));
            return;
            case 25:
            this.pathStarFive = ((System.Windows.Shapes.Path)(target));
            return;
            case 26:
            this.txtFirstReview = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.txtSecondReview = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.btnMoreReviews = ((System.Windows.Controls.Button)(target));
            return;
            case 29:
            this.btnRequestReservation = ((System.Windows.Controls.Button)(target));
            
            #line 111 "Supplier\pgViewSupplierListing.xaml"
            this.btnRequestReservation.Click += new System.Windows.RoutedEventHandler(this.btnRequestSupplier_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.btnSendMessage = ((System.Windows.Controls.Button)(target));
            return;
            case 31:
            this.grdSupplierSchedule = ((System.Windows.Controls.Grid)(target));
            return;
            case 32:
            this.txtSupplierSchedule = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.calSupplierCalendar = ((System.Windows.Controls.Calendar)(target));
            
            #line 122 "Supplier\pgViewSupplierListing.xaml"
            this.calSupplierCalendar.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.calSupplierCalendar_SelectedDatesChanged);
            
            #line default
            #line hidden
            
            #line 122 "Supplier\pgViewSupplierListing.xaml"
            this.calSupplierCalendar.DisplayDateChanged += new System.EventHandler<System.Windows.Controls.CalendarDateChangedEventArgs>(this.calSupplierCalendar_DisplayDateChanged);
            
            #line default
            #line hidden
            return;
            case 34:
            this.lblSupplierDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.datSupplierActivities = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 36:
            this.datSupplierAvailabilities = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 37:
            this.grdSupplierPricing = ((System.Windows.Controls.Grid)(target));
            return;
            case 38:
            this.txtSupplierServices = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.imageDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 40:
            this.colServiceName = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 41:
            this.colServicePrice = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 42:
            this.colServiceDescription = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 43:
            this.grdRequestSupplier = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 44:
            this.lblNameSupplierRequest = ((System.Windows.Controls.Label)(target));
            return;
            case 45:
            this.lblPhoneSupplierRequest = ((System.Windows.Controls.Label)(target));
            return;
            case 46:
            this.lblEmailSupplierRequest = ((System.Windows.Controls.Label)(target));
            return;
            case 47:
            this.cmboEventSelection = ((System.Windows.Controls.ComboBox)(target));
            
            #line 262 "Supplier\pgViewSupplierListing.xaml"
            this.cmboEventSelection.DropDownClosed += new System.EventHandler(this.cmboEventSelection_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 48:
            this.stckPnlStartAndEndTimes = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 49:
            this.chckBoxOnlyForEvents = ((System.Windows.Controls.CheckBox)(target));
            
            #line 267 "Supplier\pgViewSupplierListing.xaml"
            this.chckBoxOnlyForEvents.Checked += new System.Windows.RoutedEventHandler(this.chckBoxOnlyForEvents_Checked);
            
            #line default
            #line hidden
            
            #line 267 "Supplier\pgViewSupplierListing.xaml"
            this.chckBoxOnlyForEvents.Unchecked += new System.Windows.RoutedEventHandler(this.chckBoxOnlyForEvents_Unchecked);
            
            #line default
            #line hidden
            return;
            case 50:
            this.datePickerRequestDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 268 "Supplier\pgViewSupplierListing.xaml"
            this.datePickerRequestDate.CalendarClosed += new System.Windows.RoutedEventHandler(this.datePickerRequestDate_CalendarClosed);
            
            #line default
            #line hidden
            return;
            case 51:
            this.cmboEventDates = ((System.Windows.Controls.ComboBox)(target));
            
            #line 273 "Supplier\pgViewSupplierListing.xaml"
            this.cmboEventDates.DropDownClosed += new System.EventHandler(this.cmboEventDates_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 52:
            this.txtBlockNoDatesForEvent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 53:
            this.cmboStartandEndTimeRequest = ((WPFPresentation.CustomControls.SpecificStartAndEndTimesComboBox)(target));
            return;
            case 54:
            this.lblSelectService = ((System.Windows.Controls.Label)(target));
            return;
            case 55:
            this.scrollViewerServices = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 56:
            this.icServices = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 58:
            this.lblAdditionalComments = ((System.Windows.Controls.Label)(target));
            return;
            case 59:
            this.txtAdditionalComments = ((System.Windows.Controls.TextBox)(target));
            return;
            case 60:
            this.stckSendCancel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 61:
            this.btnSendRequest = ((System.Windows.Controls.Button)(target));
            
            #line 304 "Supplier\pgViewSupplierListing.xaml"
            this.btnSendRequest.Click += new System.Windows.RoutedEventHandler(this.btnSendRequest_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.btnCancelRequest = ((System.Windows.Controls.Button)(target));
            
            #line 305 "Supplier\pgViewSupplierListing.xaml"
            this.btnCancelRequest.Click += new System.Windows.RoutedEventHandler(this.btnCancelRequest_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 57:
            
            #line 292 "Supplier\pgViewSupplierListing.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.CheckBox_Checked);
            
            #line default
            #line hidden
            
            #line 292 "Supplier\pgViewSupplierListing.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.CheckBox_Unchecked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

