#pragma checksum "Volunteer\pgViewVolunteerDetails.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "22E6962AFA9432EC9DC8EACD7A45E2285585A8C21997B47830052C5198CE5082"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation;


namespace WPFPresentation {
    
    
    /// <summary>
    /// pgViewVolunteerDetails
    /// </summary>
    public partial class pgViewVolunteerDetails : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer scrVolunteerDetails;
        
        #line default
        #line hidden
        
        
        #line 37 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtVolunteerName;
        
        #line default
        #line hidden
        
        
        #line 38 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas canStarRating;
        
        #line default
        #line hidden
        
        
        #line 42 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarOne;
        
        #line default
        #line hidden
        
        
        #line 45 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarTwo;
        
        #line default
        #line hidden
        
        
        #line 48 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarThree;
        
        #line default
        #line hidden
        
        
        #line 51 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFour;
        
        #line default
        #line hidden
        
        
        #line 54 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path pathStarFive;
        
        #line default
        #line hidden
        
        
        #line 60 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtAboutVolunnteerName;
        
        #line default
        #line hidden
        
        
        #line 61 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxAboutVolunteer;
        
        #line default
        #line hidden
        
        
        #line 70 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtVolunteerType;
        
        #line default
        #line hidden
        
        
        #line 73 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtSkillSet;
        
        #line default
        #line hidden
        
        
        #line 74 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxSkillSet;
        
        #line default
        #line hidden
        
        
        #line 82 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgVolunteerImage;
        
        #line default
        #line hidden
        
        
        #line 83 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 84 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnNext;
        
        #line default
        #line hidden
        
        
        #line 88 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtReviews;
        
        #line default
        #line hidden
        
        
        #line 89 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtNoReviewsYet;
        
        #line default
        #line hidden
        
        
        #line 90 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxReviews;
        
        #line default
        #line hidden
        
        
        #line 91 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBoxReviewsSecond;
        
        #line default
        #line hidden
        
        
        #line 92 "Volunteer\pgViewVolunteerDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMoreReviews;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/volunteer/pgviewvolunteerdetails.xaml", System.UriKind.Relative);
            
            #line 1 "Volunteer\pgViewVolunteerDetails.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.scrVolunteerDetails = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 2:
            this.txtVolunteerName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.canStarRating = ((System.Windows.Controls.Canvas)(target));
            return;
            case 4:
            this.pathStarOne = ((System.Windows.Shapes.Path)(target));
            return;
            case 5:
            this.pathStarTwo = ((System.Windows.Shapes.Path)(target));
            return;
            case 6:
            this.pathStarThree = ((System.Windows.Shapes.Path)(target));
            return;
            case 7:
            this.pathStarFour = ((System.Windows.Shapes.Path)(target));
            return;
            case 8:
            this.pathStarFive = ((System.Windows.Shapes.Path)(target));
            return;
            case 9:
            this.txtAboutVolunnteerName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.txtBoxAboutVolunteer = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.txtVolunteerType = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.txtSkillSet = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.txtBoxSkillSet = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.imgVolunteerImage = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.txtReviews = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.txtNoReviewsYet = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.txtBoxReviews = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.txtBoxReviewsSecond = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.btnMoreReviews = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

