#pragma checksum "Volunteer\pgViewVolunteerSchedule.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "97823D77B3E660FC6A820D5BFD620B88485C4C1A52DE94D2474A2B8817C7ECE4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation;


namespace WPFPresentation {
    
    
    /// <summary>
    /// pgViewVolunteerSchedule
    /// </summary>
    public partial class pgViewVolunteerSchedule : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer scrVolunteerSchedule;
        
        #line default
        #line hidden
        
        
        #line 20 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtVolunteerSchedule;
        
        #line default
        #line hidden
        
        
        #line 21 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar calVolunteerCalendar;
        
        #line default
        #line hidden
        
        
        #line 32 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblVolunteerDate;
        
        #line default
        #line hidden
        
        
        #line 36 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datVolunteerEvents;
        
        #line default
        #line hidden
        
        
        #line 48 "Volunteer\pgViewVolunteerSchedule.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datVolunteerAvailabilities;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/volunteer/pgviewvolunteerschedule.xaml", System.UriKind.Relative);
            
            #line 1 "Volunteer\pgViewVolunteerSchedule.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Volunteer\pgViewVolunteerSchedule.xaml"
            ((WPFPresentation.pgViewVolunteerSchedule)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.scrVolunteerSchedule = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 3:
            this.txtVolunteerSchedule = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.calVolunteerCalendar = ((System.Windows.Controls.Calendar)(target));
            
            #line 21 "Volunteer\pgViewVolunteerSchedule.xaml"
            this.calVolunteerCalendar.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.calVolunteerCalendar_SelectedDatesChanged);
            
            #line default
            #line hidden
            
            #line 21 "Volunteer\pgViewVolunteerSchedule.xaml"
            this.calVolunteerCalendar.DisplayDateChanged += new System.EventHandler<System.Windows.Controls.CalendarDateChangedEventArgs>(this.calVolunteerCalendar_DisplayDateChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.lblVolunteerDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.datVolunteerEvents = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 7:
            this.datVolunteerAvailabilities = ((System.Windows.Controls.DataGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

