#pragma checksum "Volunteer\pgVolunteerFrame.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "25F2733C1B1F1074EF801FE46D4AB482100FCAB1CCD4757619E833F166DF8DD5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation;


namespace WPFPresentation {
    
    
    /// <summary>
    /// pgVolunteerFrame
    /// </summary>
    public partial class pgVolunteerFrame : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "Volunteer\pgVolunteerFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnVolunteerDetails;
        
        #line default
        #line hidden
        
        
        #line 24 "Volunteer\pgVolunteerFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnVolunteerSchedule;
        
        #line default
        #line hidden
        
        
        #line 25 "Volunteer\pgVolunteerFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnVolunteerSupplies;
        
        #line default
        #line hidden
        
        
        #line 28 "Volunteer\pgVolunteerFrame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame VolunteerFrame;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/volunteer/pgvolunteerframe.xaml", System.UriKind.Relative);
            
            #line 1 "Volunteer\pgVolunteerFrame.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "Volunteer\pgVolunteerFrame.xaml"
            ((WPFPresentation.pgVolunteerFrame)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnVolunteerDetails = ((System.Windows.Controls.Button)(target));
            
            #line 23 "Volunteer\pgVolunteerFrame.xaml"
            this.btnVolunteerDetails.Click += new System.Windows.RoutedEventHandler(this.btnVolunteerDetails_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnVolunteerSchedule = ((System.Windows.Controls.Button)(target));
            
            #line 24 "Volunteer\pgVolunteerFrame.xaml"
            this.btnVolunteerSchedule.Click += new System.Windows.RoutedEventHandler(this.btnVolunteerSchedule_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnVolunteerSupplies = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.VolunteerFrame = ((System.Windows.Controls.Frame)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

