// <auto-generated />
namespace MVCPresentationWithIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bringuptodata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bringuptodata));
        
        string IMigrationMetadata.Id
        {
            get { return "202204272209056_bring up to data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
