#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3D5CAA363384BE763B7C647ABEF407F4AA1DA0286BAC7C1BB943C03F30B249F0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ModernWpf;
using ModernWpf.Controls;
using ModernWpf.Controls.Primitives;
using ModernWpf.DesignTime;
using ModernWpf.Markup;
using ModernWpf.Media.Animation;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation;
using WPFPresentation.CustomControls;


namespace WPFPresentation {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal WPFPresentation.MainWindow frmMainWindow;
        
        #line default
        #line hidden
        
        
        #line 23 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdMainMenu;
        
        #line default
        #line hidden
        
        
        #line 75 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Viewbox btnHomeWhite;
        
        #line default
        #line hidden
        
        
        #line 93 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Viewbox btnHomeYellow;
        
        #line default
        #line hidden
        
        
        #line 111 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHome;
        
        #line default
        #line hidden
        
        
        #line 125 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.GeometryDrawing BackArrow;
        
        #line default
        #line hidden
        
        
        #line 134 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBack;
        
        #line default
        #line hidden
        
        
        #line 136 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreateEvents;
        
        #line default
        #line hidden
        
        
        #line 137 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnViewEvents;
        
        #line default
        #line hidden
        
        
        #line 138 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnViewSuppliers;
        
        #line default
        #line hidden
        
        
        #line 139 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnViewLocations;
        
        #line default
        #line hidden
        
        
        #line 140 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnViewVolunteers;
        
        #line default
        #line hidden
        
        
        #line 141 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnViewAbout;
        
        #line default
        #line hidden
        
        
        #line 188 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem mnuUser;
        
        #line default
        #line hidden
        
        
        #line 189 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem mnuLogOut;
        
        #line default
        #line hidden
        
        
        #line 194 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame MainFrame;
        
        #line default
        #line hidden
        
        
        #line 211 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock staLoginMsg;
        
        #line default
        #line hidden
        
        
        #line 215 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock staCurrentPageMsg;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.frmMainWindow = ((WPFPresentation.MainWindow)(target));
            return;
            case 2:
            this.grdMainMenu = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.btnHomeWhite = ((System.Windows.Controls.Viewbox)(target));
            return;
            case 4:
            this.btnHomeYellow = ((System.Windows.Controls.Viewbox)(target));
            return;
            case 5:
            this.btnHome = ((System.Windows.Controls.Button)(target));
            
            #line 111 "MainWindow.xaml"
            this.btnHome.Click += new System.Windows.RoutedEventHandler(this.btnHome_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BackArrow = ((System.Windows.Media.GeometryDrawing)(target));
            return;
            case 7:
            this.btnBack = ((System.Windows.Controls.Button)(target));
            
            #line 134 "MainWindow.xaml"
            this.btnBack.Click += new System.Windows.RoutedEventHandler(this.btnBack_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btnCreateEvents = ((System.Windows.Controls.Button)(target));
            
            #line 136 "MainWindow.xaml"
            this.btnCreateEvents.Click += new System.Windows.RoutedEventHandler(this.btnCreateEvents_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btnViewEvents = ((System.Windows.Controls.Button)(target));
            
            #line 137 "MainWindow.xaml"
            this.btnViewEvents.Click += new System.Windows.RoutedEventHandler(this.btnViewEvents_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnViewSuppliers = ((System.Windows.Controls.Button)(target));
            
            #line 138 "MainWindow.xaml"
            this.btnViewSuppliers.Click += new System.Windows.RoutedEventHandler(this.btnViewSuppliers_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnViewLocations = ((System.Windows.Controls.Button)(target));
            
            #line 139 "MainWindow.xaml"
            this.btnViewLocations.Click += new System.Windows.RoutedEventHandler(this.btnViewLocations_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnViewVolunteers = ((System.Windows.Controls.Button)(target));
            
            #line 140 "MainWindow.xaml"
            this.btnViewVolunteers.Click += new System.Windows.RoutedEventHandler(this.btnViewVolunteers_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnViewAbout = ((System.Windows.Controls.Button)(target));
            return;
            case 14:
            this.mnuUser = ((System.Windows.Controls.MenuItem)(target));
            return;
            case 15:
            this.mnuLogOut = ((System.Windows.Controls.MenuItem)(target));
            
            #line 189 "MainWindow.xaml"
            this.mnuLogOut.Click += new System.Windows.RoutedEventHandler(this.mnuLogOut_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.MainFrame = ((System.Windows.Controls.Frame)(target));
            
            #line 194 "MainWindow.xaml"
            this.MainFrame.Navigated += new System.Windows.Navigation.NavigatedEventHandler(this.MainFrame_Navigated);
            
            #line default
            #line hidden
            return;
            case 17:
            this.staLoginMsg = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.staCurrentPageMsg = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

