#pragma checksum "CustomControls\SpecificStartAndEndTimesComboBox.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "36F16903C9B54D3347E26033D9CF4CE3755D180740A833DC48DFD0D1522077F8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WPFPresentation.CustomControls;


namespace WPFPresentation.CustomControls {
    
    
    /// <summary>
    /// SpecificStartAndEndTimesComboBox
    /// </summary>
    public partial class SpecificStartAndEndTimesComboBox : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 27 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboStartHour;
        
        #line default
        #line hidden
        
        
        #line 28 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboEndHour;
        
        #line default
        #line hidden
        
        
        #line 31 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStartHourError;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPresentation;component/customcontrols/specificstartandendtimescombobox.xaml", System.UriKind.Relative);
            
            #line 1 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.cmboStartHour = ((System.Windows.Controls.ComboBox)(target));
            
            #line 27 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
            this.cmboStartHour.DropDownClosed += new System.EventHandler(this.cmboStartHour_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 2:
            this.cmboEndHour = ((System.Windows.Controls.ComboBox)(target));
            
            #line 28 "CustomControls\SpecificStartAndEndTimesComboBox.xaml"
            this.cmboEndHour.DropDownClosed += new System.EventHandler(this.cmboEndHour_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 3:
            this.txtStartHourError = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

